spring:
  application:
    name: fetch
server:
  port: 19093

minio:
  url: ${MINIO_URL}
  access:
    key: minio
    secret: minioadmin
  buckets:
    downloadBucket: mybucket
    uploadBucket: update-bucket  # 수정된 부분

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL} # Eureka 서버 URL
    register-with-eureka: true  # Eureka 서버에 등록
    fetch-registry: true  # Eureka 서버로부터  정보 가져오기