spring:
  application:
    name: upload
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  servlet:
    multipart:
      max-file-size: 10MB # 최대 파일 사이즈
      max-request-size: 10MB # 최대 요청 사이즈

server:
  port: 19092

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:19090/eureka/

minio:
  url: http://localhost:9000
  accessKey: minio
  secretKey: minioadmin
  bucket: mybucket

data-server:
  url: localhost:19095

cdn-server:
  url: http://localhost:19096/cdn
