spring:
  application:
    name: internal
  datasource:
    url: jdbc:postgresql://localhost:5432/server_data
    username: server_data_db
    password: server_data_db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        highlight_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 19094

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:19090/eureka/

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace

minio:
  url: http://localhost:9000
  access:
    key: minio
    secret: minioadmin
  buckets:
    downloadBucket: original-bucket
    uploadBucket: update-bucket  # 수정된 부분
